### ISSUE TITLE
Help me for defconfig file Realme7

### ISSUE THREAD

**Issue by smileyNeha** [kardebayan/kernel_oppo_CPH1859#1]
Hello sir
 I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?

Which defconfig for realme7/narzo20 pro devices?

**Comment by devil-black-786** [comment]
@smileyNeha Find Ur  Self miss

**Comment by CyberJalagam** [comment]
> Hello sir
> I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> 
> Which defconfig for realme7/narzo20 pro devices?

Wtf has that have to do with this kernel 😂

**Comment by techyminati** [comment]
> Hello sir
> I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> 
> Which defconfig for realme7/narzo20 pro devices?

This is realme 1 kernel tho

> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> Wtf has that have to do with this ker

> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> Wtf has that have to do with this kernel 😂



> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> Wtf has that have to do with this kernel 😂

realme 1 != realme 7 , i guess

**Comment by devil-black-786** [comment]
@techyminati this is GitHub please go away 😂

**Comment by CyberJalagam** [comment]
> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> This is realme 1 kernel tho
> 
> > > Hello sir
> > > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > > Which defconfig for realme7/narzo20 pro devices?
> > 
> > 
> > Wtf has that have to do with this ker
> 
> > > Hello sir
> > > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > > Which defconfig for realme7/narzo20 pro devices?
> > 
> > 
> > Wtf has that have to do with this kernel 😂
> 
> > > Hello sir
> > > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > > Which defconfig for realme7/narzo20 pro devices?
> > 
> > 
> > Wtf has that have to do with this kernel 😂
> 
> realme 1 != realme 7 , i guess

Lol

**Comment by CyberJalagam** [comment]
Bot going like brr brr

**Comment by techyminati** [comment]
> @techyminati this is GitHub please go away 😂

Perro 👍

**Comment by CyberJalagam** [comment]
@techyminati

**Comment by techyminati** [comment]
> Bot going like brr brr

I'm not using bot lmao, I'm on git repo itself, Perro 👍

**Comment by CyberJalagam** [comment]
@techyminati Nunu wut i mean is the github bot in our group is going like brr brr

**Comment by techyminati** [comment]
> @techyminati Nunu wut i mean is the github bot in our group is going like brr brr

Perro 👍, Wen tell RMX2185 defconfig sor

**Comment by SahilSonar** [comment]
> Hello sir
> I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> 
> Which defconfig for realme7/narzo20 pro devices?

How about reading the documentation?

**Comment by CyberJalagam** [comment]
> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> How about reading the documentation?

OoO cartel raid😂😂

**Comment by sarthakroy2002** [comment]
> Hello sir
> I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> 
> Which defconfig for realme7/narzo20 pro devices?

try trinket defconfig

**Comment by devil-black-786** [comment]
@sarthakroy2002 Full Spam Baji

**Comment by techyminati** [comment]
> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> try trinket defconfig

N , where is realme1_defconfig , i cant see help need kernel for pubg

**Comment by kardebayan** [comment]
@smileyNeha no idea, I left realme 7 long ago

**Comment by CyberJalagam** [comment]
@kardebayan *sed smoiley noices*

**Comment by ad1tyas1ngh** [comment]
> @techyminati this is GitHub please go away 😂

Teach wen saar? 👊😎

**Comment by sarthakroy2002** [comment]
> > > Hello sir
> > > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > > Which defconfig for realme7/narzo20 pro devices?
> > 
> > 
> > try trinket defconfig
> 
> N , where is realme1_defconfig , i cant see help need kernel for pubg

no @smileyNeha needs Qualcomm 69fps in G95 gheymer chip

**Comment by sarthakroy2002** [comment]
> @sarthakroy2002 Full Spam Baji

spam!=sperm sar..so i caME

**Comment by CyberJalagam** [comment]
@sarthakroy2002 smoiley ai: hold my beer 🍻

**Comment by techyminati** [comment]
> @sarthakroy2002 smoiley ai: hold my beer 🍻

@CyberJalagam How's this btw https://github.com/kardebayan/kernel_oppo_CPH1859/commit/6f8052cf0c559be2ca84a5a91ed0379d1505877a

**Comment by ad1tyas1ngh** [comment]
> @sarthakroy2002 smoiley ai: hold my beer 🍻

Lmaoo😂

**Comment by CyberJalagam** [comment]
> > @sarthakroy2002 smoiley ai: hold my beer beers
> 
> @CyberJalagam How's this btw [6f8052c](https://github.com/kardebayan/kernel_oppo_CPH1859/commit/6f8052cf0c559be2ca84a5a91ed0379d1505877a)

wot abt dis 03b11791549e7533fc1e7f559832f3e24b973aaf

**Comment by techyminati** [comment]
@CyberJalagam yeah thats cool, when for doin it for  https://github.com/techyminati/android_kernel_realme_mt6765 btw

**Comment by sarthakroy2002** [comment]
> @sarthakroy2002 smoiley ai: hold my beer 🍻

FDE.AI = smoiley ai
Haters will say its kanged
Smoiley will say... FDE kanged

**Comment by Maitreya29** [comment]
> Hello sir
> I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> 
> Which defconfig for realme7/narzo20 pro devices?

Hi, please ignore these people.

https://raw.githubusercontent.com/Maitreya29/TanjiroKernelOP5-T/custom2/arch/arm64/configs/tanjiro_defconfig

Take this file and put it in arch/arm64/boot/mediatek_overclock-defconfig

**Comment by kardebayan** [comment]
> 
> 
> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> Hi, please ignore these people.
> 
> https://raw.githubusercontent.com/Maitreya29/TanjiroKernelOP5-T/custom2/arch/arm64/configs/tanjiro_defconfig
> 
> Take this file and put it in arch/arm64/boot/mediatek_overclock-defconfig

This should work

**Comment by techyminati** [comment]
> > > Hello sir
> > > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > > Which defconfig for realme7/narzo20 pro devices?
> > 
> > 
> > Hi, please ignore these people.
> > https://raw.githubusercontent.com/Maitreya29/TanjiroKernelOP5-T/custom2/arch/arm64/configs/tanjiro_defconfig
> > Take this file and put it in arch/arm64/boot/mediatek_overclock-defconfig
> 
> This should work

No , Thats wrong, I guess this should work : https://raw.githubusercontent.com/torvalds/linux/master/arch/arm64/configs/defconfig

**Comment by kardebayan** [comment]
@techyminati i tried this for confirmation on my realme 1 kernel and it worked fine

**Comment by techyminati** [comment]
> @techyminati i tried this for confirmation on my realme 1 kernel and it worked fine

are you sure @kardebayan

**Comment by kardebayan** [comment]
@techyminati yup thanks for increasing my knowledge and also now i got performance boost like my helio p60 now works like helio g95

**Comment by Hunter-commits** [comment]
> @sarthakroy2002 smoiley ai: hold my beer 🍻

😂😂😂

**Comment by NitroVenom** [comment]
> > @sarthakroy2002 smoiley ai: hold my beer 🍻
> 
> FDE.AI = smoiley ai
> Haters will say its kanged
> Smoiley will say... FDE kanged

No bro, i checked smiley AI it is 20 parallel universe ahead of FDE. Many lines repeat twice. Also her build prop twerk is soo pro, for example- 

Ro.fps.enable=1 this enables fps pubg 
Debug.performance.tuning=1 google not tune performance! Smiley ai tune it by pasting this line in build prop two time vro

**Comment by NitroVenom** [comment]
And also smiley AI has converted realme 1 into realme 7, wow soo pru artificial intelligence. A AI that can convert realme 1 into realme 7 can also convert redmi note 4 into OnePlus 8 pro 🥴

**Comment by JamieHoSzeYui** [comment]
> > Hello sir
> > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > Which defconfig for realme7/narzo20 pro devices?
> 
> Wtf has that have to do with this kernel joy

use trinket_defconfig bro it's best defconfig

**Comment by sarthakroy2002** [comment]
> > > Hello sir
> > > I make new kernel Realme 7/narzo 20 pro I don't know about defconfig can you help me?
> > > Which defconfig for realme7/narzo20 pro devices?
> > 
> > 
> > Wtf has that have to do with this kernel joy
> 
> use trinket_defconfig bro it's best defconfig

That's what I said

**Comment by sarthakroy2002** [comment]
> And also smiley AI has converted realme 1 into realme 7, wow soo pru artificial intelligence. A AI that can convert realme 1 into realme 7 can also convert redmi note 4 into OnePlus 8 pro 🥴

turu

**Comment by devil-black-786** [comment]
@sarthakroy2002 doi bish

**Comment by herobuxx** [comment]
O.o

Pru kernal debaloper

**Comment by herobuxx** [comment]
Realmeme should hire smiley, ngl.
