### ISSUE TITLE
Bro whoi you nu help smoiley?

### ISSUE THREAD

**Issue by ad1tyas1ngh** [kardebayan/kernel_oppo_CPH1859#2]
🤨🤨

**Comment by CyberJalagam** [comment]
@ad1tyas1ngh gheybayan's kranul going brr brrr

**Comment by ad1tyas1ngh** [comment]
> @ad1tyas1ngh gheybayan's kranul going brr brrr

That's whoi i say sur please tax sur halp he nu lissen😭

**Comment by kardebayan** [comment]
@ad1tyas1ngh 😢
